name: mitocheck_data2
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.8.13
  - conda-forge::jupyter=1.0.0
  - conda-forge::pandas=1.4.2
  - conda-forge::scikit-image=0.19.3
  - conda-forge::pytorch=1.11.0
  - conda-forge::cellpose=2.0.5
  - pip:
    - pyimagej==1.2.1
